src/api/urls.py
from django.urls import path, re_path
from drf_yasg import openapi
from drf_yasg.views import get_schema_view
from rest_framework.routers import SimpleRouter

from api.views import AutoViewSet, MainApiView

router = SimpleRouter()
router.register('auto', AutoViewSet, 'auto_api')

schema_view = get_schema_view(
   openapi.Info(
      title="Avito API",
      default_version='v1',
      description="This is avito api",
      terms_of_service="https://www.google.com/policies/terms/",
      contact=openapi.Contact(email="anvar00755@mail.ru"),
      license=openapi.License(name="ANVAR License"),
   ),
   public=True,
)

urlpatterns = [
   path('', MainApiView.as_view(), name='main_api_view'),
   *router.urls,
   re_path('swagger(?P<format>\.json|\.yaml)$', schema_view.without_ui(cache_timeout=0), name='schema-json'),
   path('swagger/', schema_view.with_ui('swagger', cache_timeout=0), name='schema-swagger-ui'),
   path('redoc/', schema_view.with_ui('redoc', cache_timeout=0), name='schema-redoc'),
]

src/avito/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('estate/', include('real_estate.urls')),
    path('transport/', include('transport.urls')),
    path('api/', include('api.urls')),
    path('', include('main.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/transport/urls.py
from django.urls import path, re_path

from transport.views import *

urlpatterns = [
    path('auto/', AutoListView.as_view(), name='auto'),
    path('special/', SpecialTransportListView.as_view(), name='special'),
    path('moto/', MotorcycleListView.as_view(), name='moto'),

    re_path(r'^auto/(?P<pk>\d+)/$', AutoDetailView.as_view(), name='auto_detail'),
    re_path(r'^special/(?P<pk>\d+)/$', SpecialTransportDetailView.as_view(), name='special_detail'),
    re_path(r'^moto/(?P<pk>\d+)/$', MotorcycleDetailView.as_view(), name='moto_detail'),

    path('auto/create/', AutoCreateView.as_view(), name='create_auto'),
    path('special/create/', SpecialAutoCreateView.as_view(), name='create_special'),
    path('moto/create/', MotorcycleCreateView.as_view(), name='create_moto'),
]

src/transport/models.py
from django.db import models
from django.urls import reverse

from main.models import AnnouncementAbstractModel


class MarksModel(models.Model):
    name = models.CharField(max_length=60, verbose_name='Марка')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Марка'
        verbose_name_plural = 'Марки'
        ordering = ['name']


class AutoTypeModel(models.Model):
    name = models.CharField(max_length=60, verbose_name='Модель')
    mark = models.ForeignKey(MarksModel, on_delete=models.CASCADE, verbose_name='Марка')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Модель'
        verbose_name_plural = 'Модели'
        ordering = ['name']


MILEAGE_CHOICES = [
    ('broken', 'Битый'),
    ('not broken', 'Не битый')
]


class TransportAbstractModel(AnnouncementAbstractModel):
    # Appearance
    color = models.CharField(max_length=25, blank=False, null=False, verbose_name='Цвет техники')

    # Specifications
    mark = models.ForeignKey(MarksModel, on_delete=models.CASCADE, null=False, blank=False, verbose_name='Марка')
    year_of_issue = models.PositiveIntegerField(null=False, blank=False, verbose_name='Год выпуска')
    modification = models.CharField(max_length=30, null=False, blank=False, verbose_name='Объем и мощность двигателя')
    transmission = models.CharField(max_length=30, null=False, blank=False, verbose_name='Коробка передач')
    equipment = models.CharField(max_length=30, default='Базовая', verbose_name='Комплектация')

    # Operating history and condition
    mileage = models.CharField(max_length=30, choices=MILEAGE_CHOICES, blank=False, null=False, verbose_name='Состояние')
    owners = models.PositiveIntegerField(blank=False, null=False, verbose_name='Владельцев по ПТС')

    class Meta:
        abstract = True


class AutoModel(TransportAbstractModel):
    model = models.ForeignKey(AutoTypeModel, on_delete=models.CASCADE, null=False, blank=False, verbose_name='Модель')

    def get_absolute_url(self):
        return reverse('auto_detail', kwargs={'pk': self.id})

    def __str__(self):
        return '%s %s, %s' % (self.mark, self.model, self.year_of_issue)

    class Meta:
        ordering = ['-id']
        verbose_name = 'Автомобиль'
        verbose_name_plural = 'Автомобили'


class SpecialTransportModel(TransportAbstractModel):
    model = models.CharField(max_length=15, null=False, blank=False, verbose_name='Модель')
    body_type = models.CharField(max_length=15, null=False, blank=False, verbose_name='Тип кузова')
    engine_hours = models.PositiveIntegerField(null=False, blank=False, verbose_name='Моточасы')

    def get_absolute_url(self):
        return reverse('special_detail', kwargs={'pk': self.id})

    def __str__(self):
        return '%s %s, %s' % (self.mark, self.model, self.year_of_issue)

    class Meta:
        ordering = ['-id']
        verbose_name = 'Спец Техника'
        verbose_name_plural = 'Спец Техника'


class MotorcycleModel(AnnouncementAbstractModel):
    engine_hours = models.PositiveIntegerField(null=False, blank=False, verbose_name='Моточасы')

    def get_absolute_url(self):
        return reverse('moto_detail', kwargs={'pk': self.id})

    class Meta:
        ordering = ['-id']
        verbose_name = 'Мотоцикл'
        verbose_name_plural = 'Мотоциклы'

src/transport/forms.py
from main.forms import AnnouncementCreateForm
from transport.models import SpecialTransportModel, AutoModel, MotorcycleModel


class SpecialTransportForm(AnnouncementCreateForm):
    class Meta:
        model = SpecialTransportModel
        exclude = ['user']


class AutoForm(AnnouncementCreateForm):
    class Meta:
        model = AutoModel
        exclude = ['user']


class MotorcycleForm(AnnouncementCreateForm):
    class Meta:
        model = MotorcycleModel
        exclude = ['user']

src/transport/views.py
from django.urls import reverse_lazy
from django.views.generic import ListView, CreateView, DetailView

from main.views import AnnouncementCreateView, AnnouncementListView
from transport.forms import AutoForm, SpecialTransportForm, MotorcycleForm
from transport.models import AutoModel, SpecialTransportModel, MotorcycleModel
from main.services import get_model_search


class AutoListView(AnnouncementListView):
    model = AutoModel
    template_name = 'transport/auto_list.html'


class AutoDetailView(DetailView):
    model = AutoModel
    template_name = 'transport/auto_details.html'


class SpecialTransportListView(AnnouncementListView):
    model = SpecialTransportModel
    template_name = 'transport/special_list.html'


class SpecialTransportDetailView(DetailView):
    model = SpecialTransportModel
    template_name = 'transport/special_details.html'


class MotorcycleListView(AnnouncementListView):
    model = MotorcycleModel
    template_name = 'transport/moto_list.html'


class MotorcycleDetailView(DetailView):
    model = MotorcycleModel
    template_name = 'transport/moto_details.html'


class AutoCreateView(AnnouncementCreateView):
    form_class = AutoForm
    template_name = 'main/announcement_create.html'

    # def post(self, request, *args, **kwargs):
    #     print('----------------------------------------------------------------------------')
    #     print(request.POST)
    #     form = self.get_form()
    #     print(form.errors)
    #     super().post(request, *args, **kwargs)

    def get_success_url(self):
        return reverse_lazy('auto')


class SpecialAutoCreateView(AnnouncementCreateView):
    form_class = SpecialTransportForm
    template_name = 'main/announcement_create.html'

    def get_success_url(self):
        return reverse_lazy('special')


class MotorcycleCreateView(AnnouncementCreateView):
    form_class = MotorcycleForm
    template_name = 'main/announcement_create.html'

    def get_success_url(self):
        return reverse_lazy('moto')

src/transport/templates/transport/layout/transport_announcement.html
{% extends "main/layouts/announcement.html" %}

{% block announcement %}
    {% block transport_announcement %}{% endblock %}

    <ul class="list-group">
        {% if object.color %}
            <li class="list-group-item">Цвет: {{ object.color }}</li>
        {% endif %}
        {% if object.equipment %}
            <li class="list-group-item">Комплектация: {{ object.equipment }}</li>
        {% endif %}
        {% if object.mileage %}
            <li class="list-group-item">Состояние: {{ object.get_mileage_display }}</li>
        {% endif %}
        {% if object.owners %}
            <li class="list-group-item">Владельцев по ПТС: {{ object.owners }}</li>
        {% endif %}
        {% if object.mark %}
            <li class="list-group-item">Марка: {{ object.mark }}</li>
        {% endif %}
        {% if object.year_of_issue %}
            <li class="list-group-item">Год выпуска: {{ object.year_of_issue }}</li>
        {% endif %}
        {% if object.modification %}
            <li class="list-group-item">Объем и мощность двигателя: {{ object.modification }}</li>
        {% endif %}
        {% if object.transmission %}
            <li class="list-group-item">Коробка передач: {{ object.transmission }}</li>
        {% endif %}
    </ul>

{% endblock %}

src/transport/templates/transport/layout/transport_list.html
{% extends 'main/layouts/announcement_list.html' %}

{% block title %}
    Транспорт в городе
    {% if city %}
        {{ city }}
    {% else %}Казань{% endif %}
{% endblock %}

{% block announcement_list %}
    <div class="col-3 content__nav">
            <nav class="nav flex-column">
                <a class="nav-link" href="{% url 'auto' %}">Автомобили</a>
                <a class="nav-link" href="{% url 'moto' %}">Мотоциклы</a>
                <a class="nav-link" href="{% url 'special' %}">Спецтехника</a>
            </nav>
        </div>
        <div class="col-8 content__announcements">

            {% block transport_list %}{% endblock %}

        </div>
{% endblock %}